name: modbld

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: install haxe
        uses: HaxeFoundation/setup-haxe@v2.0.3
        with:
          haxe-version: 4.2.5
      - name: install libs
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install hxcpp --quiet
          haxelib install linc_luajit --quiet
          haxelib install discord_rpc --quiet
          haxelib install hscript --quiet
      - name: fix discord_rpc native lib
        run: |
          $base = "C:/hostedtoolcache/windows/haxe/4.2.5/x64/lib/discord_rpc"
          $version = Get-ChildItem $base | Select-Object -First 1 -ExpandProperty Name
          $libPath = "$base/$version/lib"
          Write-Host "Cloning into: $libPath/discord-rpc"
          New-Item -ItemType Directory -Force -Path $libPath
          git clone https://github.com/discord/discord-rpc.git "$libPath/discord-rpc"
        shell: pwsh
      - name: build
        run: haxelib run lime build windows
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: fnf-build
          path: export/release/windows/bin
