name: modbld

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: install haxe
        uses: HaxeFoundation/setup-haxe@v2.0.3
        with:
          haxe-version: 4.2.5
      - name: install libs
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install hxcpp --quiet
          haxelib install linc_luajit --quiet
          haxelib install discord_rpc --quiet
      - name: build
        run: haxelib run lime build windows
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: fnf-build
          path: export/release/windows/bin
